name: Smoke Tests


on:
 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Web Application
        run: docker compose -f compose.dev.yml up -d

      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install additional dependencies if needed
          pip install -r requirements.txt
          rfbrowser init


      - name: Run Smoke Tests
        run: robot --exclude smoke --listener RetryFailed e2e-tests\   


  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Web Application
        run: docker compose -f compose.dev.yml up -d

      

      - name: Install dependencies
        run: |
          sudo apt-get update
          # Install additional dependencies if needed
          sudo apt-get install k6
      - name: Run Smoke Tests
        run: k6 run run load_testing\load_test.js  
       
      
      

      

      
